#!/bin/bash
mkdir -p /Users/trinadh/projects/petstore/stitch_screens

echo "Downloading Shop Profile..."
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/shop_profile.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2I4YTgxZDE4ZDQyMjRmNGFhZDg4YTk0OThjZGFiNjJhEgsSBxDsgsvU9BUYAZIBIwoKcHJvamVjdF9pZBIVQhM2NjA0ODQ1MTU2MTczODYwOTA0&filename=&opi=89354086"
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/shop_profile.png "https://lh3.googleusercontent.com/aida/AP1WRLvY1BRqAYgrMJxKpP3yRMecG3RaeIBLCwYZps-cIGwGcuJEIe9eU67eMtiRp_17fXzZPRjADMPVq2qU_N-L96tKOtNzwh8bJjRhtgF0vvASAUrlvc3GVUll2jTkhUF5ESdoJlUUVxAyCbdwlHmosv_HJmQLUgGf8Y02tkop6pnDTA7osUoPxcHrd0MH7ETDatdOEinztVl1NfnForIPU8Y21MMFWY648Bpw6su3a35augw8ZkceMGHGaqY"

echo "Downloading Vaccinations & Tablets..."
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/vaccinations_tablets.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sX2Q3ZTc5NDVmZDQ5YjRlN2U5ZjdhOWZlMTRlZGYxYzlhEgsSBxDsgsvU9BUYAZIBIwoKcHJvamVjdF9pZBIVQhM2NjA0ODQ1MTU2MTczODYwOTA0&filename=&opi=89354086"
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/vaccinations_tablets.png "https://lh3.googleusercontent.com/aida/AP1WRLsJeQelEL9hlUBD4WeEeTd2WQHEpt0iQtPAMjPN_O086MPydy3zDYMXPFAHn8TPzdTqVLWnYdfMQISt5sLHAXSqQ7vPkgXSS_L_0pZ8V7wFRIdus1wQGGjhjY_UUg0vPYJEs4LkSaBAgKKRyESO0shDaFAKP_Dg0VmiVi9ZjxibdnavQSxAPWQ3XeDGoyETXmuEFqCUL80RKFsOp49mNp7gsiBBoczC5IMnKd3IsZpxeRUMmmZTSohMiH0"

echo "Downloading Orders..."
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/orders_updated.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzU2N2VkZGVmYzAyYjQ1OGNiNTBhYjNjYmNiNzg5NjM1EgsSBxDsgsvU9BUYAZIBIwoKcHJvamVjdF9pZBIVQhM2NjA0ODQ1MTU2MTczODYwOTA0&filename=&opi=89354086"
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/orders_updated.png "https://lh3.googleusercontent.com/aida/AP1WRLuH-KbLiJ8hUu-qFxTZ9I1U3ixsJqine4O9oDGzbzSa4fkS6cznfzmTy2G48eeO_axo_SkCSkjXhnTDhx9WHSSAISPRH8N8tZnwlM6PJ3r3cPv_A9cSGFZioB6krQAmuQ8uGbw_NAwoKTKYl7XkzHjmWqbcTGUpNzk4uC-8VEd3Xl7fUZbg_L-HWPfQVpOtSdpMVttyPCNJJ7hbHP3iJiPj6aJB8DVNWySwPvQEVJhzUIB5RfSnudreZoU"

echo "Downloading Favourites..."
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/favourites_updated.html "https://contribution.usercontent.google.com/download?c=CgthaWRhX2NvZGVmeBJ7Eh1hcHBfY29tcGFuaW9uX2dlbmVyYXRlZF9maWxlcxpaCiVodG1sXzNmOTg1M2IxZjcxYjRjOTFhYmVlZDcxMmQwMDc0OWMyEgsSBxDsgsvU9BUYAZIBIwoKcHJvamVjdF9pZBIVQhM2NjA0ODQ1MTU2MTczODYwOTA0&filename=&opi=89354086"
curl -L -o /Users/trinadh/projects/petstore/stitch_screens/favourites_updated.png "https://lh3.googleusercontent.com/aida/AP1WRLsFPeR5X4rnl50eIDUwnkecJKrv8HJyMlQeuiCZDAN0g0aEk-wKTnID9w4FdVtFgJlJBQiK8zDSruHlDw8ZFkdgYdb7Dk-hEMQPebX1MldWoHh0biY7TlJzdmMwUj_6_IYEvRiA1XxCaRrqj4w6En_3j_LBpBY-aQ4G7-0ZVxO-4M1ccTHM6bpIk9fPQDqSp4fsK_71KS9uoaQHSkxVE6KMuwDKGZxnNXV0BdYep0PKfCDh1ZVfk0Rjjwc"

echo "All downloads complete."
