package com.example.ui

import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.setValue

object L10n {
    var currentLanguage by mutableStateOf("en")

    private val translations = mapOf(
        "en" to mapOf(
            "app_name" to "Swiggy Paws",
            "splash_tagline" to "Premium Pet Shop Delivery Platform",
            "skip" to "Skip",
            "next" to "Next",
            "get_started" to "Get Started",
            "login" to "Login",
            "register" to "Register",
            "logout" to "Log out of Swiggy Paws",
            "email_or_phone" to "Email or Phone Number",
            "password" to "Password",
            "login_btn" to "Login with Password",
            "forgot_password" to "Forgot Password? Login via Phone OTP 🔑",
            "back_to_password_login" to "Back to Email/Password Login 🔐",
            "phone_number" to "Phone Number",
            "mock_otp_hint" to "Use any mock OTP (e.g. 1234) to proceed",
            "enter_mock_otp" to "Enter 4-Digit OTP",
            "send_otp" to "Send OTP",
            "verify_and_login" to "Verify & Login",
            "full_name" to "Full Name",
            "select_city_title" to "Select Delivery Location",
            "select_city_desc" to "Choose your city to see available stores and grooming services.",
            "search_placeholder" to "Search for pet food, toys, clinics...",
            "tab_explore" to "Explore",
            "tab_wishlist" to "Wishlist",
            "tab_chats" to "Chats",
            "tab_profile" to "Profile",
            "looking_for_today" to "What are you looking for today?",
            "premium_shops_nearby" to "Premium Pet Shops Nearby",
            "grooming_spas" to "Grooming & Spas",
            "emergency_vet_services" to "Emergency Vet Services",
            "add_to_cart" to "Add",
            "cart_replace_title" to "Replace Cart Items?",
            "cart_replace_desc" to "Your cart contains items from another shop. Would you like to clear your current cart and add items from dynamic shop?",
            "cancel" to "Cancel",
            "clear_and_add" to "Clear & Add",
            "my_cart" to "My Cart",
            "bill_details" to "Bill Details",
            "item_total" to "Item Total",
            "delivery_fee" to "Delivery Fee",
            "taxes_charges" to "Taxes & Charges",
            "to_pay" to "To Pay",
            "delivery_address" to "Delivery Address",
            "add_instructions" to "Add cooking/delivery instructions...",
            "proceed_checkout" to "Proceed to Checkout",
            "saved_wishlist" to "Saved Wishlist",
            "care_calendar" to "Care Calendar & Reminders",
            "change_city" to "Change City Location",
            "super_admin_controls" to "Super Admin Controls",
            "logout_btn" to "Log out of Swiggy Paws",
            "select_language" to "Select Language",
            "language_subtitle" to "Change app language to English, Hindi, or Telugu",
            "select_language_title" to "Choose Language",
            "onboarding_title_1" to "City-Wide Pet Shops & Foods",
            "onboarding_desc_1" to "Find premium nutritional kibbles, grain-free snacks, and toys from recruited pet stores across the entire city.",
            "onboarding_title_2" to "Premium Grooming & Spas",
            "onboarding_desc_2" to "Connect with top-rated salons and vet clinics in your city. Schedule professional bathes and pet therapy easily.",
            "onboarding_title_3" to "Express Delivery Anywhere",
            "onboarding_desc_3" to "Order from top recruited pet stores in the city and get ultra-fast delivery straight to your doorstep.",
            "status_pending" to "Order Placed",
            "desc_pending" to "Your order has been registered by Swiggy Paws",
            "status_accepted" to "Order Accepted",
            "desc_accepted" to "The merchant clinic has confirmed and verified stock",
            "status_preparing" to "Preparing Delivery",
            "desc_preparing" to "Dog items are packed carefully under clean standards",
            "status_out_for_delivery" to "Out for Delivery",
            "desc_out_for_delivery" to "Delivering directly via secure local dog service",
            "status_delivered" to "Delivered successfully",
            "desc_delivered" to "Package received by dog parent"
        ),
        "te" to mapOf(
            "app_name" to "స్విగ్గీ పాస్",
            "splash_tagline" to "ప్రీమియం పెట్ షాప్ డెలివరీ ప్లాట్‌ఫారమ్",
            "skip" to "దాటవేయి",
            "next" to "తరువాత",
            "get_started" to "ప్రారంభించండి",
            "login" to "లాగిన్",
            "register" to "నమోదు",
            "logout" to "స్విగ్గీ పాస్ నుండి లాగ్ అవుట్ అవ్వండి",
            "email_or_phone" to "ఈమెయిల్ లేదా ఫోన్ నంబర్",
            "password" to "పాస్‌వర్డ్",
            "login_btn" to "పాస్‌వర్డ్‌తో లాగిన్ చేయండి",
            "forgot_password" to "పాస్‌వర్డ్ మర్చిపోయారా? ఫోన్ OTP ద్వారా లాగిన్ అవ్వండి 🔑",
            "back_to_password_login" to "ఈమెయిల్/పాస్‌వర్డ్ లాగిన్‌కు తిరిగి వెళ్ళండి 🔐",
            "phone_number" to "ఫోన్ నంబర్",
            "mock_otp_hint" to "ముందుకు సాగడానికి ఏదైనా మాక్ OTP (ఉదా. 1234) ఉపయోగించండి",
            "enter_mock_otp" to "4-అంకెల OTPని నమోదు చేయండి",
            "send_otp" to "OTP పంపండి",
            "verify_and_login" to "ధృవీకరించి లాగిన్ చేయండి",
            "full_name" to "పూర్తి పేరు",
            "select_city_title" to "డెలివరీ స్థానాన్ని ఎంచుకోండి",
            "select_city_desc" to "అందుబాటులో ఉన్న దుకాణాలు మరియు గ్రూమింగ్ సేవలను చూడటానికి మీ నగరాన్ని ఎంచుకోండి.",
            "search_placeholder" to "పెట్ ఫుడ్, బొమ్మలు, క్లినిక్‌ల కోసం వెతకండి...",
            "tab_explore" to "అన్వేషించండి",
            "tab_wishlist" to "ఇష్టమైనవి",
            "tab_chats" to "చాట్లు",
            "tab_profile" to "ప్రొఫైల్",
            "looking_for_today" to "ఈరోజు మీరు ఏమి వెతుకుతున్నారు?",
            "premium_shops_nearby" to "దగ్గరలోని ప్రీమియం పెట్ షాపులు",
            "grooming_spas" to "గ్రూమింగ్ & స్పా సేవలు",
            "emergency_vet_services" to "అత్యవసర పశువైద్య సేవలు",
            "add_to_cart" to "జతచేయి",
            "cart_replace_title" to "కార్ట్ వస్తువులను భర్తీ చేయాలా?",
            "cart_replace_desc" to "మీ కార్ట్‌లో మరొక దుకాణం నుండి వస్తువులు ఉన్నాయి. మీ ప్రస్తుత కార్ట్‌ను క్లియర్ చేసి, ఈ వస్తువులను జోడించాలనుకుంటున్నారా?",
            "cancel" to "రద్దు చేయి",
            "clear_and_add" to "క్లియర్ & యాడ్",
            "my_cart" to "నా కార్ట్",
            "bill_details" to "బిల్లు వివరాలు",
            "item_total" to "వస్తువుల మొత్తం",
            "delivery_fee" to "డెలివరీ ఛార్జీ",
            "taxes_charges" to "పన్నులు & ఇతర ఛార్జీలు",
            "to_pay" to "చెల్లించవలసిన మొత్తం",
            "delivery_address" to "డెలివరీ చిరునామా",
            "add_instructions" to "వంట/డెలివరీ సూచనలను జోడించండి...",
            "proceed_checkout" to "చెక్అవుట్ చేయడానికి కొనసాగండి",
            "saved_wishlist" to "సేవ్ చేసిన ఇష్టమైనవి",
            "care_calendar" to "రక్షణ క్యాలెండర్ & రిమైండర్లు",
            "change_city" to "నగర స్థానాన్ని మార్చండి",
            "super_admin_controls" to "సూపర్ అడ్మిన్ నియంత్రణలు",
            "logout_btn" to "లాగ్ అవుట్ చేయండి",
            "select_language" to "భాషను ఎంచుకోండి",
            "language_subtitle" to "యాప్ భాషను ఇంగ్లీష్, హిందీ లేదా తెలుగులోకి మార్చండి",
            "select_language_title" to "భాషను ఎంచుకోండి",
            "onboarding_title_1" to "నగరమంతటా పెట్ షాపులు & ఆహారం",
            "onboarding_desc_1" to "నగరవ్యాప్తంగా ఉన్న పెట్ స్టోర్‌ల నుండి ప్రీమియం పోషకమైన కిబుల్స్, ధాన్యం లేని స్నాక్స్ మరియు బొమ్మలను కనుగొనండి.",
            "onboarding_title_2" to "ప్రీమియం గ్రూమింగ్ & స్పాస్",
            "onboarding_desc_2" to "మీ నగరంలోని టాప్-రేటెడ్ సెలూన్‌లు మరియు వెట్ క్లినిక్‌లతో కనెక్ట్ అవ్వండి. ప్రొఫెషనల్ బాత్‌లు మరియు పెట్ థెరపీని సులభంగా షెడ్యూల్ చేయండి.",
            "onboarding_title_3" to "ఎక్కడైనా ఎక్స్‌ప్రెస్ డెలివరీ",
            "onboarding_desc_3" to "నగరంలోని ప్రముఖ పెట్ స్టోర్‌ల నుండి ఆర్డర్ చేయండి మరియు మీ ఇంటి వద్దకే అతి వేగంగా డెలివరీ పొందండి.",
            "status_pending" to "ఆర్డర్ విజయవంతంగా చేయబడింది",
            "desc_pending" to "మీ ఆర్డర్ స్విగ్గీ పాస్ ద్వారా నమోదు చేయబడింది",
            "status_accepted" to "ఆర్డర్ అంగీకరించబడింది",
            "desc_accepted" to "షాప్ యాజమాన్యం మీ ఆర్డర్ మరియు స్టాక్‌ను నిర్ధారించింది",
            "status_preparing" to "డెలివరీ సిద్ధం చేయబడుతోంది",
            "desc_preparing" to "మీ పెంపుడు జంతువు వస్తువులు శుభ్రమైన పద్ధతిలో ప్యాక్ చేయబడుతున్నాయి",
            "status_out_for_delivery" to "డెలివరీకి బయలుదేరింది",
            "desc_out_for_delivery" to "డెలివరీ భాగస్వామి మీ ఇంటికి బయలుదేరారు",
            "status_delivered" to "డెలివరీ చేయబడింది",
            "desc_delivered" to "ప్యాకేజీ పెంపుడు జంతువుల యజమానికి విజయవంతంగా అందింది"
        ),
        "hi" to mapOf(
            "app_name" to "स्वीगी पॉज़",
            "splash_tagline" to "प्रीमियम पेट शॉप डिलीवरी प्लेटफॉर्म",
            "skip" to "छोड़ें",
            "next" to "अगला",
            "get_started" to "शुरू करें",
            "login" to "लॉगिन",
            "register" to "पंजीकरण",
            "logout" to "स्वीगी पॉज़ से लॉग आउट करें",
            "email_or_phone" to "ईमेल या फोन नंबर",
            "password" to "पासवर्ड",
            "login_btn" to "पासवर्ड के साथ लॉगिन करें",
            "forgot_password" to "पासवर्ड भूल गए? फोन ओटीपी द्वारा लॉगिन करें 🔑",
            "back_to_password_login" to "ईमेल/पासवर्ड लॉगिन पर वापस जाएं 🔐",
            "phone_number" to "फ़ोन नंबर",
            "mock_otp_hint" to "आगे बढ़ने के लिए किसी भी मॉक ओटीपी (जैसे 1234) का उपयोग करें",
            "enter_mock_otp" to "4-अंकीय ओटीपी दर्ज करें",
            "send_otp" to "ओटीपी भेजें",
            "verify_and_login" to "सत्यापित करें और लॉगिन करें",
            "full_name" to "पूरा नाम",
            "select_city_title" to "डिलीवरी स्थान चुनें",
            "select_city_desc" to "उपलब्ध स्टोर और ग्रूमिंग सेवाओं को देखने के लिए अपना शहर चुनें।",
            "search_placeholder" to "पालतू जानवरों के भोजन, खिलौने, क्लीनिक खोजें...",
            "tab_explore" to "अन्वेषण",
            "tab_wishlist" to "विशलिस्ट",
            "tab_chats" to "चैट",
            "tab_profile" to "प्रोफ़ाइल",
            "looking_for_today" to "आज आप क्या ढूंढ रहे हैं?",
            "premium_shops_nearby" to "आसपास के प्रीमियम पेट शॉप्स",
            "grooming_spas" to "ग्रूमिंग और स्पा",
            "emergency_vet_services" to "आपातकालीन पशु चिकित्सक सेवाएं",
            "add_to_cart" to "जोड़ें",
            "cart_replace_title" to "कार्ट आइटम बदलें?",
            "cart_replace_desc" to "आपकी कार्ट में दूसरे स्टोर के आइटम हैं। क्या आप अपनी वर्तमान कार्ट को खाली करके इस आइटम को जोड़ना चाहते हैं?",
            "cancel" to "रद्द करें",
            "clear_and_add" to "खाली करें और जोड़ें",
            "my_cart" to "मेरी कार्ट",
            "bill_details" to "बिल विवरण",
            "item_total" to "आइटम कुल",
            "delivery_fee" to "डिलीवरी शुल्क",
            "taxes_charges" to "कर और शुल्क",
            "to_pay" to "कुल भुगतान",
            "delivery_address" to "डिलीवरी का पता",
            "add_instructions" to "कुकिंग/डिलीवरी निर्देश जोड़ें...",
            "proceed_checkout" to "चेकआउट के लिए आगे बढ़ें",
            "saved_wishlist" to "सुरक्षित विशलिस्ट",
            "care_calendar" to "देखभाल कैलेंडर और अनुस्मारक",
            "change_city" to "शहर का स्थान बदलें",
            "super_admin_controls" to "सुपर एडमिन नियंत्रण",
            "logout_btn" to "लॉग आउट करें",
            "select_language" to "भाषा चुनें",
            "language_subtitle" to "ऐप की भाषा अंग्रेजी, हिंदी या तेलुगु में बदलें",
            "select_language_title" to "भाषा चुनें",
            "onboarding_title_1" to "शहर भर में पेट शॉप्स और फूड",
            "onboarding_desc_1" to "पूरे शहर में पेट स्टोर से प्रीमियम पौष्टिक भोजन, अनाज मुक्त स्नैक्स और खिलौने खोजें।",
            "onboarding_title_2" to "प्रीमियम ग्रूमिंग और स्पा",
            "onboarding_desc_2" to "अपने शहर के टॉप-रेटेड सैलून और पशु चिकित्सक क्लीनिकों से जुड़ें। आसानी से स्नान और पेट थेरेपी का समय तय करें।",
            "onboarding_title_3" to "कहीं भी एक्सप्रेस डिलीवरी",
            "onboarding_desc_3" to "शहर के प्रमुख पेट स्टोर से ऑर्डर करें और अपने दरवाजे पर सुपर-फास्ट डिलीवरी पाएं।",
            "status_pending" to "ऑर्डर दिया गया",
            "desc_pending" to "आपका ऑर्डर स्वीगी पॉज़ द्वारा पंजीकृत किया गया है",
            "status_accepted" to "ऑर्डर स्वीकार किया गया",
            "desc_accepted" to "दुकानदार ने आपका ऑर्डर और स्टॉक स्वीकार कर लिया है",
            "status_preparing" to "डिलिवरी की तैयारी हो रही है",
            "desc_preparing" to "पालतू जानवरों का सामान स्वच्छ तरीके से पैक किया जा रहा है",
            "status_out_for_delivery" to "डिलिवरी के लिए रवाना",
            "desc_out_for_delivery" to "डिलिवरी पार्टनर आपके घर के लिए निकल चुका है",
            "status_delivered" to "सफलतापूर्वक वितरित किया गया",
            "desc_delivered" to "पालतू जानवर के माता-पिता को पैकेज प्राप्त हो गया है"
        )
    )

    fun getString(key: String): String {
        return translations[currentLanguage]?.get(key)
            ?: translations["en"]?.get(key)
            ?: key
    }
}
